name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-interaction --no-scripts --no-progress
    - name: Generate application key
      run: php artisan key:generate
    - name: Generate authenticate key
      run: php artisan jwt:secret -n
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Validate open api
      run: php ./vendor/bin/openapi ./app 1> /dev/null
    - name: Validate php stan
      run: php ./vendor/bin/phpstan analyse
    - name: Validate php code sniffer
      run: php ./vendor/bin/phpcs
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --configuration phpunit.xml
